[workspace]
authors = ["Steve Pieper <pieper@isomics.com>"]
channels = ["conda-forge"]
name = "slicer-discourse-archive"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
pip = ">=26.0.1,<27"
requests = ">=2.31,<3"
